services:
  equip-lease:
    container_name: equip-lease
    build:
      context: ./src
      dockerfile: Dockerfile
    ports:
      - "5242:5242"
    environment:
      DatabaseConnectionString: "Data Source=mssql;Initial Catalog=EquipLeaseDb;User id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=true;"
    depends_on:
      - mssql
  
  mssql:
    container_name: sql-server
    # image: mcr.microsoft.com/mssql/server:2022-latest
    image: mcr.microsoft.com/azure-sql-edge:latest
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "YourStrong!Passw0rd"
      MSSQL_PID: "Developer"
    ports:
      - 1433:1433
    volumes:
      - ./mssql-data:/var/opt/mssql/data